### ISSUE TITLE
切换菜单后，右侧内容未未切换

### ISSUE THREAD

**Issue by lyBigdata** [yixiaco/ruoyi-tdesign#45]
![image](https://github.com/yixiaco/ruoyi-tdesign/assets/13713204/c25a7e3e-1ed3-4abe-a4ed-1d10986cd404)
切换菜单后，右侧内容未未切换？

**Comment by yixiaco** [comment]
没办法重现你说的问题哈，看你的ip显示应该是在开发环境编译运行吧，第一次加载页面需要等待vite编译懒加载的组件，因此点击后需要等待后台编译完成后重新点击菜单就能够进入页面了。
或者你可以发一个可以复现的步骤给我看看

**Comment by yixiaco** [comment]
我在主分支更新依赖后也出现你说的问题，等待我更新最新的补丁

**Comment by yixiaco** [comment]
请查看最新的提交

**Comment by lyBigdata** [comment]
可以了，感谢
