### ISSUE TITLE
关于点击任意菜单后，加载数据页面为空的问题

### ISSUE THREAD

**Issue by StarryCrystal** [yixiaco/ruoyi-tdesign#5]
使用版本(未按照模板填写直接删除)
jdk版本(带上尾号): ZuluJdk11-11.0.19
框架版本(项目启动时输出的版本号): Vite 4.3.9 && Tdesign@0.7.1
其他依赖版本(你觉得有必要的): Springboot2版本，原来接近Ruoyi基础功能的版本

问题前提
早期的版本，在前台有点击一个页面，内容为空的情况，要刷新这个页面才会加载内容，最近看到发现这个问题已经修复。但是没有发现提交的代码中有修改该问题的地方，想请问是修改哪里达成的效果？

异常模块
ruoyi-ui

问题描述
用户登录后，点击任意一个模块，出现内容为空，不请求不加载任何数据的情况
点击任意一个模块
![image](https://github.com/yixiaco/ruoyi-tdesign/assets/17041926/ff53ebfb-c346-4708-bd71-9c3dcd2cee8a)
问题截图
![image](https://github.com/yixiaco/ruoyi-tdesign/assets/17041926/929a3c3f-33ca-4c7b-93c4-69f691aad097)
然后刷新整个页面后，数据就可以正常加载

希望结果
新版的ruoyi-tdesign我fork下来后，发现问题已经解决，想请问是怎么解决的？

相关代码与报错信息
无任何报错

**Comment by yixiaco** [comment]
重复问题：https://gitee.com/yixiacoco/ruoyi-tdesign/issues/I7IAHO
