### ISSUE TITLE
main分支，刚才更新之后，登录页无法加载了，不清楚是什么问题

### ISSUE THREAD

**Issue by lyBigdata** [yixiaco/ruoyi-tdesign#51]
main分支，刚才更新之后，登录页无法加载了，不清楚是什么问题

**Comment by yixiaco** [comment]
应该跟这个更新有关系:[fix 修复 session 多账号共用覆盖问题 改为 tokenSession 独立存储（需要清理redis缓存，否则会报错）](https://github.com/yixiaco/ruoyi-tdesign/commit/f560242100551cfc683765bee4f0e55c3a7d5e33)
这是一个同步自RuoyiVuePlus的提交

**Comment by yixiaco** [comment]
问题已经修复，请更新到最新代码
