### ISSUE TITLE
租户角色修改有问题

### ISSUE THREAD

**Issue by LinYing89** [yixiaco/ruoyi-tdesign#66]
使用租户账号登录, 修改角色界面,  报错, 找不到ew属性, 在SysMenuMapper这个接口的selectMenuListByUserId方法, 在对应的xml文件中有${ew.getCustomSqlSegment}代码, 找不到ew对象或字段
![image](https://github.com/yixiaco/ruoyi-tdesign/assets/30618832/a013101c-d05e-4c29-a3bb-a0bde8b53905)

**Comment by yixiaco** [comment]
好的哈，能帮忙排查一下，如果将${ew.getCustomSqlSegment}删除后，功能是否正常。
![image](https://github.com/yixiaco/ruoyi-tdesign/assets/30982989/547a3243-e8cd-4b37-af95-9b1db6bc61ad)

**Comment by LinYing89** [comment]
删除后是正常的, 不知道这一句有没有用

**Comment by yixiaco** [comment]
> 删除后是正常的, 不知道这一句有没有用

好的，这一句没有用了，是原有的功能，测试没到位。
