### ISSUE TITLE
无法切换语言，切换语言时报错

### ISSUE THREAD

**Issue by EricGG-0** [yixiaco/ruoyi-tdesign#68]
前端项目源代码直接运行，报错如下
![iShot_2024-05-06_16 51 36](https://github.com/yixiaco/ruoyi-tdesign/assets/17738551/e087898c-281d-4987-8d62-75f4b76e2437)

当我注释掉 message.msgSuccess(t('constants.switchLanguage'));
报错如下
![iShot_2024-05-06_16 52 55](https://github.com/yixiaco/ruoyi-tdesign/assets/17738551/34bbe47c-f713-4ed3-8d23-4d78c74f1258)

**Comment by yixiaco** [comment]
因为开发环境没办法复现你说的问题，麻烦提供下代码版本、Vue的版本和运行环境、复现过程

**Comment by EricGG-0** [comment]
代码版本 是最新版本   1.3.0 


https://github.com/yixiaco/ruoyi-tdesign/assets/17738551/49576f44-0b46-4b12-a63a-5408f3c44bbd

**Comment by EricGG-0** [comment]
node 版本是 v20.4.0

**Comment by yixiaco** [comment]
https://github.com/yixiaco/ruoyi-tdesign/assets/30982989/832cc16e-3ab2-4f67-8625-dc3bdd59c230

有其他更多的信息吗，我这边没办法复现这个问题

**Comment by EricGG-0** [comment]
你把 node_modules文件夹删掉，重新 npm install 呢？

**Comment by yixiaco** [comment]
> 你把 node_modules文件夹删掉，重新 npm install 呢？

重新安装还是无法复现，你的包使用的yarn install安装吗，这个项目使用的包管理器是yarn
